### ISSUE TITLE
Dockerize project

### ISSUE THREAD

**Issue by robsmithw** [robsmithw/FinanceTracking#8]
All three parts of this solution should be able to be put into a docker container so that pulling/building/publishing this project is easier.

There should be a docker-compose.yml set up that should take care of building all three parts by running `docker-compose up`.

The three parts need to be built in the following order
1) MySQL 5.7 image set up with root password (refer to Readme.md for information on database name and password for root)
2) Python API (FinanceTrackingAPI) - Dependent on MySQL db being built first (Python API initializes the DB - that configuration will need to be modified)
3) Angular frontend (FinanceTrackingUI) - Dependent on Python API being built first

**Comment by parkedwards** [comment]
@robsmithw I can take this one

**Comment by robsmithw** [comment]
> @robsmithw I can take this one

Sounds good, thanks! Let me know if you have any questions or need some help.
